import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
    await page.getByRole('heading', { name: 'Welcome back, Mind Gym' }).click();
    await page.getByRole('link', { name: 'icon Surveys' }).first().click();
    await page.getByRole('link', { name: 'Create New Survey' }).click();
    await page.getByRole('textbox', { name: 'Enter survey name' }).click();
    await page.getByRole('textbox', { name: 'Enter survey name' }).fill('Judith Benjamin');
    await page.locator('trix-editor').click();
    await page.locator('trix-editor').fill('This looks awesome to us');
    await page.getByRole('textbox', { name: 'Enter Estimated Time To' }).click();
    await page.getByRole('textbox', { name: 'Enter Estimated Time To' }).fill('1 min');
    await page.getByRole('textbox', { name: 'Enter question' }).click();
    await page.getByRole('textbox', { name: 'Enter question' }).fill('Similique earum aspe');
    await page.getByRole('alert').filter({ hasText: 'Scale' }).click();
    await page.getByText('Hundred Point Scale').click();
    await page.getByRole('combobox').filter({ hasText: 'Survey SectionNo results' }).locator('i').click();
    await page.getByText('Add Survey Section').click();
    await page.getByRole('textbox', { name: 'Type survey section title...' }).click();
    await page.getByRole('textbox', { name: 'Type survey section title...' }).fill('awesome');
    await page.getByText('Add', { exact: true }).click();
    await page.getByRole('button', { name: 'Add Question' }).click();
    await page.getByRole('textbox', { name: 'Enter question' }).click();
    await page.getByRole('textbox', { name: 'Enter question' }).fill('Quia sint dolores v');
    await page.getByRole('listbox').locator('i').click();
    await page.getByRole('option', { name: 'Scale', exact: true }).click();
    await page.locator('div').filter({ hasText: /^SurveySend a survey link to respondents to complete within a 30-day window\.$/ }).first().click();
    await page.getByRole('checkbox').nth(1).check();
    await page.getByRole('checkbox').nth(3).check();
    await page.getByRole('button', { name: 'Save & Review' }).click();
    await page.getByRole('link', { name: 'Exit' }).click();
    await page.locator('#assessment-15 i').click();
    await page.locator('#dropdown-overlay').click();
    await page.locator('#assessment-15').getByRole('link').click();
    await page.getByText('None (0)All (1)Unassigned (1)').click();
    await page.getByText('All (1)').click();
    await page.getByRole('button', { name: 'Save & Review' }).click();
    await page.getByText('Send').click();
    await expect(page.getByText('collecting', { exact: true })).toBeVisible();
});